name = "gloutozore"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gloutozore-db"
database_id = "" # will be filled after `wrangler d1 create gloutozore-db`
