name = "gloutozore"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gloutozore-db"
database_id = "f9cb6752-c78d-4f4b-949d-6e864ac2aae3"
